title: Harold Choi # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of Analytics at RMIT student with a Bachelor of Commerce seeking opportunities in the data and technology industry. 
  Experience at fintech and AI startups, multinational professional services and banks working on projects and initiatives varying in size and complexity.
  <br><br>
  <a href="https://www.linkedin.com/in/harold-choi-344980170/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
